import { Property, Agent, Testimonial, Service, Stat } from "@/types";

export const agents: Agent[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    title: "Senior Property Consultant",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    phone: "+1 (555) 234-5678",
    email: "sarah@estateprime.com",
    rating: 4.9,
    totalSales: 247,
    totalListings: 12,
    experience: 12,
    bio: "Sarah specializes in luxury residential properties and has helped over 240 families find their dream homes in the greater metropolitan area.",
    specialties: ["Luxury Homes", "Waterfront Properties", "New Construction"],
    socialLinks: {
      linkedin: "#",
      twitter: "#",
      instagram: "#",
    },
  },
  {
    id: "2",
    name: "James Harrington",
    title: "Commercial Real Estate Expert",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    phone: "+1 (555) 345-6789",
    email: "james@estateprime.com",
    rating: 4.8,
    totalSales: 189,
    totalListings: 8,
    experience: 9,
    bio: "James brings deep expertise in commercial real estate, investment properties, and portfolio management with a track record of premium deals.",
    specialties: ["Commercial", "Investment Properties", "Industrial"],
    socialLinks: {
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: "3",
    name: "Elena Vasquez",
    title: "Residential Specialist",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    phone: "+1 (555) 456-7890",
    email: "elena@estateprime.com",
    rating: 4.9,
    totalSales: 315,
    totalListings: 15,
    experience: 15,
    bio: "Elena is one of our top performers with 15+ years of experience, known for her exceptional negotiation skills and client-first approach.",
    specialties: ["Residential", "Condos", "First-time Buyers"],
    socialLinks: {
      linkedin: "#",
      twitter: "#",
      instagram: "#",
    },
  },
  {
    id: "4",
    name: "Marcus Thompson",
    title: "Luxury Property Advisor",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    phone: "+1 (555) 567-8901",
    email: "marcus@estateprime.com",
    rating: 4.7,
    totalSales: 142,
    totalListings: 6,
    experience: 7,
    bio: "Marcus focuses on ultra-luxury properties and penthouse apartments, with an exclusive network of high-net-worth clients worldwide.",
    specialties: ["Ultra-Luxury", "Penthouses", "International Buyers"],
    socialLinks: {
      linkedin: "#",
      instagram: "#",
    },
  },
];

export const properties: Property[] = [
  {
    id: "1",
    title: "Willow Heights Penthouse",
    address: "1200 Park Avenue",
    city: "New York",
    state: "NY",
    price: 4850000,
    priceUnit: "sale",
    type: "penthouse",
    status: "for-sale",
    bedrooms: 4,
    bathrooms: 3,
    area: 3800,
    areaUnit: "sqft",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80",
    ],
    description:
      "Experience unparalleled luxury in this stunning penthouse featuring panoramic city views, designer finishes, and world-class amenities. The open-plan living spaces are bathed in natural light through floor-to-ceiling windows.",
    features: [
      "Panoramic City Views",
      "Private Rooftop Terrace",
      "Chef's Kitchen",
      "Smart Home System",
      "Concierge Service",
      "Private Elevator",
    ],
    agent: agents[0],
    yearBuilt: 2022,
    garage: 2,
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    views: 1847,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    title: "Cedar Ridge Villa",
    address: "45 Lakeview Drive",
    city: "Beverly Hills",
    state: "CA",
    price: 7200000,
    priceUnit: "sale",
    type: "villa",
    status: "featured",
    bedrooms: 6,
    bathrooms: 5,
    area: 6200,
    areaUnit: "sqft",
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    ],
    description:
      "An architectural masterpiece nestled in the prestigious hills of Beverly Hills. This magnificent villa combines classic elegance with contemporary design, featuring resort-style amenities and breathtaking mountain views.",
    features: [
      "Infinity Pool",
      "Home Theater",
      "Wine Cellar",
      "Gym & Spa",
      "Guest House",
      "Smart Automation",
    ],
    agent: agents[3],
    yearBuilt: 2020,
    garage: 4,
    isFeatured: true,
    isNew: false,
    rating: 5.0,
    views: 3241,
    createdAt: "2023-11-20",
  },
  {
    id: "3",
    title: "Oak Wood Residence",
    address: "78 Maple Street",
    city: "Austin",
    state: "TX",
    price: 985000,
    priceUnit: "sale",
    type: "house",
    status: "for-sale",
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    areaUnit: "sqft",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80",
    ],
    description:
      "A beautifully crafted family home in one of Austin's most sought-after neighborhoods. Features an open floor plan, gourmet kitchen, and a stunning backyard perfect for entertaining.",
    features: [
      "Open Floor Plan",
      "Gourmet Kitchen",
      "Master Suite",
      "Backyard Oasis",
      "Home Office",
      "3-Car Garage",
    ],
    agent: agents[2],
    yearBuilt: 2021,
    garage: 3,
    isFeatured: true,
    isNew: false,
    rating: 4.7,
    views: 924,
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    title: "Skyline Loft Apartment",
    address: "350 Urban Boulevard",
    city: "Chicago",
    state: "IL",
    price: 4500,
    priceUnit: "rent",
    rentPeriod: "month",
    type: "apartment",
    status: "for-rent",
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    areaUnit: "sqft",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    ],
    description:
      "Modern industrial-chic loft in the heart of downtown Chicago. High ceilings, exposed brick, and floor-to-ceiling windows create a dramatic living space with stunning city views.",
    features: [
      "City Views",
      "Exposed Brick",
      "High Ceilings",
      "Rooftop Access",
      "In-unit Laundry",
      "Doorman",
    ],
    agent: agents[1],
    yearBuilt: 2019,
    garage: 1,
    isFeatured: true,
    isNew: true,
    rating: 4.6,
    views: 567,
    createdAt: "2024-03-10",
  },
  {
    id: "5",
    title: "Harbor View Condo",
    address: "88 Waterfront Way",
    city: "Miami",
    state: "FL",
    price: 1750000,
    priceUnit: "sale",
    type: "condo",
    status: "for-sale",
    bedrooms: 3,
    bathrooms: 2,
    area: 2100,
    areaUnit: "sqft",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    ],
    description:
      "Stunning waterfront condo offering breathtaking harbor views from every room. Premium finishes, resort-style amenities, and direct beach access make this a truly exceptional property.",
    features: [
      "Ocean Views",
      "Private Beach Access",
      "Pool & Spa",
      "Fitness Center",
      "Covered Parking",
      "24hr Security",
    ],
    agent: agents[0],
    yearBuilt: 2023,
    garage: 2,
    isFeatured: true,
    isNew: true,
    rating: 4.8,
    views: 1523,
    createdAt: "2024-03-01",
  },
  {
    id: "6",
    title: "Mountain Retreat Estate",
    address: "234 Alpine Road",
    city: "Aspen",
    state: "CO",
    price: 5900000,
    priceUnit: "sale",
    type: "house",
    status: "for-sale",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    areaUnit: "sqft",
    images: [
      "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&q=80",
      "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
    ],
    description:
      "A magnificent mountain retreat offering seclusion and luxury at its finest. Ski-in/ski-out access, vaulted ceilings, and a massive stone fireplace create an unforgettable alpine experience.",
    features: [
      "Ski-in/Ski-out",
      "Stone Fireplace",
      "Vaulted Ceilings",
      "Hot Tub",
      "Game Room",
      "Mountain Views",
    ],
    agent: agents[3],
    yearBuilt: 2018,
    garage: 3,
    isFeatured: false,
    isNew: false,
    rating: 4.9,
    views: 2105,
    createdAt: "2023-12-05",
  },
  {
    id: "7",
    title: "The Greenwich Townhouse",
    address: "12 Heritage Lane",
    city: "Greenwich",
    state: "CT",
    price: 2800000,
    priceUnit: "sale",
    type: "house",
    status: "for-sale",
    bedrooms: 5,
    bathrooms: 4,
    area: 3600,
    areaUnit: "sqft",
    images: [
      "https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    ],
    description:
      "Timeless elegance meets modern comfort in this exquisite Greenwich townhouse. Located in a prestigious neighborhood with excellent schools, this property offers the perfect blend of luxury and family living.",
    features: [
      "Period Details",
      "Modern Kitchen",
      "Library",
      "Formal Gardens",
      "Wine Room",
      "Mudroom",
    ],
    agent: agents[2],
    yearBuilt: 2015,
    garage: 2,
    isFeatured: false,
    isNew: false,
    rating: 4.6,
    views: 782,
    createdAt: "2024-01-28",
  },
  {
    id: "8",
    title: "Azure Bay Apartment",
    address: "501 Pacific Coast Hwy",
    city: "Malibu",
    state: "CA",
    price: 8500,
    priceUnit: "rent",
    rentPeriod: "month",
    type: "apartment",
    status: "for-rent",
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    areaUnit: "sqft",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    ],
    description:
      "Wake up to stunning Pacific Ocean views every morning in this beautifully appointed Malibu apartment. Direct beach access, modern interiors, and a prime location make this an extraordinary rental opportunity.",
    features: [
      "Direct Beach Access",
      "Ocean Views",
      "Private Deck",
      "Gourmet Kitchen",
      "Fireplace",
      "Carport",
    ],
    agent: agents[0],
    yearBuilt: 2017,
    garage: 1,
    isFeatured: false,
    isNew: true,
    rating: 4.8,
    views: 1089,
    createdAt: "2024-03-15",
  },
];

export const featuredProperties = properties.filter((p) => p.isFeatured);

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Rebecca Chen",
    role: "Home Buyer",
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    content:
      "EstatePrime made finding my dream home an absolute joy. Sarah was incredibly knowledgeable and patient throughout the entire process. We found the perfect property within two weeks!",
    rating: 5,
    date: "2024-02-15",
    propertyType: "Luxury Home",
  },
  {
    id: "2",
    name: "David Morrison",
    role: "Property Investor",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    content:
      "As a seasoned investor, I've worked with many agencies. EstatePrime stands out for their market expertise and professionalism. James helped me close three investment properties at below-market rates.",
    rating: 5,
    date: "2024-01-20",
    propertyType: "Investment Properties",
  },
  {
    id: "3",
    name: "Sophia Laurent",
    role: "First-Time Buyer",
    avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    content:
      "Being a first-time buyer, I was nervous about the whole process. Elena held my hand every step of the way, explained everything clearly, and I got a fantastic deal on my condo!",
    rating: 5,
    date: "2024-03-01",
    propertyType: "Condo",
  },
  {
    id: "4",
    name: "Michael Zhang",
    role: "Home Seller",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    content:
      "I sold my property 15% above asking price, all thanks to EstatePrime's marketing strategy. Professional photography, virtual tours, and targeted outreach made all the difference.",
    rating: 5,
    date: "2024-02-28",
    propertyType: "Family Home",
  },
  {
    id: "5",
    name: "Amanda Foster",
    role: "Relocating Professional",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    content:
      "Relocating across the country is stressful, but EstatePrime made the real estate part seamless. Virtual tours, detailed neighborhood reports, and a dedicated agent made it feel effortless.",
    rating: 5,
    date: "2024-01-10",
    propertyType: "Apartment",
  },
  {
    id: "6",
    name: "Robert Kim",
    role: "Luxury Home Buyer",
    avatar: "https://randomuser.me/api/portraits/men/61.jpg",
    content:
      "Marcus helped us find a penthouse that exceeded our expectations. His knowledge of the luxury market and his exclusive network gave us access to properties not yet on the public market.",
    rating: 5,
    date: "2024-03-10",
    propertyType: "Penthouse",
  },
];

export const services: Service[] = [
  {
    id: "1",
    icon: "Home",
    title: "Buy a Property",
    description:
      "Find your perfect home from our curated selection of premium properties across the country. Our experts guide you through every step.",
    features: [
      "Personalized property matching",
      "Neighborhood analysis reports",
      "Price negotiation expertise",
      "Legal & financial guidance",
    ],
  },
  {
    id: "2",
    icon: "TrendingUp",
    title: "Sell Your Property",
    description:
      "Maximize your property's value with our proven marketing strategies, professional staging, and extensive buyer network.",
    features: [
      "Professional photography & video",
      "Strategic pricing analysis",
      "Targeted marketing campaigns",
      "Seamless closing process",
    ],
  },
  {
    id: "3",
    icon: "Key",
    title: "Rent & Lease",
    description:
      "Whether you're a tenant searching or a landlord listing, we make the rental process effortless and profitable.",
    features: [
      "Tenant screening & verification",
      "Lease agreement assistance",
      "Property management options",
      "Rental market analysis",
    ],
  },
  {
    id: "4",
    icon: "BarChart2",
    title: "Property Investment",
    description:
      "Build long-term wealth through strategic real estate investment with our expert portfolio management and market insights.",
    features: [
      "ROI analysis & forecasting",
      "Investment portfolio review",
      "Market trend reports",
      "Tax optimization guidance",
    ],
  },
];

export const stats: Stat[] = [
  {
    value: 15,
    suffix: "+",
    label: "Years of Excellence",
    description: "Serving clients across the nation",
  },
  {
    value: 4200,
    suffix: "+",
    label: "Happy Clients",
    description: "Families found their dream home",
  },
  {
    value: 8500,
    suffix: "+",
    label: "Properties Listed",
    description: "Premium listings nationwide",
  },
  {
    value: 98,
    suffix: "%",
    label: "Client Satisfaction",
    description: "5-star rating consistency",
  },
];

export const propertyTypes = [
  { value: "all", label: "All Types" },
  { value: "house", label: "House" },
  { value: "apartment", label: "Apartment" },
  { value: "condo", label: "Condo" },
  { value: "villa", label: "Villa" },
  { value: "penthouse", label: "Penthouse" },
  { value: "commercial", label: "Commercial" },
];

export const statusOptions = [
  { value: "all", label: "Buy & Rent" },
  { value: "for-sale", label: "For Sale" },
  { value: "for-rent", label: "For Rent" },
];

export const priceRanges = [
  { value: "0-500000", label: "Under $500K" },
  { value: "500000-1000000", label: "$500K - $1M" },
  { value: "1000000-3000000", label: "$1M - $3M" },
  { value: "3000000-10000000", label: "$3M - $10M" },
  { value: "10000000+", label: "$10M+" },
];

export const cityOptions = [
  { value: "all", label: "All Cities" },
  { value: "New York", label: "New York, NY" },
  { value: "Beverly Hills", label: "Beverly Hills, CA" },
  { value: "Miami", label: "Miami, FL" },
  { value: "Chicago", label: "Chicago, IL" },
  { value: "Austin", label: "Austin, TX" },
  { value: "Aspen", label: "Aspen, CO" },
  { value: "Malibu", label: "Malibu, CA" },
];
